---
# tasks file for aws-httpd-vpc-subnet
- name: Get my current IP address
  uri:
    url: http://checkip.amazonaws.com/
    return_content: yes
  register: my_ip

- debug:
    var: my_ip

- debug: 
    var: my_ip.content
- pip:
    name: boto
- pip:
    name: boto3

- name: create VPC
  ec2_vpc_net:
     name: "{{ vpc_name }}"
     cidr_block: "{{ vpc_cidr }}"
     region: "{{ region }}"
     state: present
  register: vpc

- debug:
    var: vpc

- name: Set VPC ID in variable
  set_fact:
    vpc_id: "{{ vpc.vpc.id }}"

  register: vpcid

- debug:
    var: vpcid
- debug: 
    var: vpcid.ansible_facts.vpc_id

- debug:
    var: vpc.vpc.id
- debug: 
    var: vpc.vpc.id

- debug: 
    var: vpc.vpc.cidr_block

- debug: 
    var: vpc.vpc.cidr_block_association_set[0].association_id

- debug: 
    var: vpc.vpc.tags.Name

- name: associate subnet to the VPC
  ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    cidr: "{{ subnet_cidr }}"
    map_public: yes
    resource_tags:
      Name: "{{ subnet_name }}"
  register: subnet

- debug:
    var: subnet

- debug: 
    var: subnet.subnet.id
- debug: 
    var: subnet.subnet.vpc_id

- debug: 
    var: subnet.subnet.cidr_block

- debug: 
    var: subnet.subnet.id

- debug: 
    var: subnet.subnet.tags.Name

- debug: 
    var: subnet.subnet.vpc_id


- name: create IGW
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    state: "present"
    tags:
      Name: "{{ igw_name }}"
  register: igw

- debug: 
    var: igw
- debug: 
    var: igw.vpc_id
- debug: 
    var: igw.gateway_id

- debug: 
    var: igw.tags.Name

- debug: 
    var: igw.vpc_id


- name: Route IGW
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    subnets:
      - "{{ subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id  }}"
    tags:
      Name: "{{ route_name }}"
  register: rigw

- debug:
    var: rigw

- debug: 
    var: rigw.route_table.associations[0].route_table_association_id

- debug: 
    var: rigw.route_table.associations[0].route_table_id

- debug: 
    var: rigw.route_table.associations[0].subnet_id

- debug:
    var:  rigw.route_table.id

- debug:
    var:  rigw.route_table.route_table_id

- debug:
    var:  rigw.route_table.routes[0].destination_cidr_block

- debug:
    var:  rigw.route_table.routes[0].gateway_id

- debug:
    var:  rigw.route_table.routes[1].destination_cidr_block

- debug:
    var:  rigw.route_table.routes[1].gateway_id

- debug: 
    var: rigw.route_table.tags.Name

- debug: 
    var: rigw.route_table.vpc_id



- name: Create Security Group
  ec2_group:
    name: Web DMZ
    description: DMZ Security Group
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
        - 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        ports:
        - 22
        cidr_ip: 0.0.0.0/0
  register: security_group

- debug:
    var: security_group

- debug: 
    var: security_group.group_id
- debug: 
    var: security_group.group_name
- debug: 
    var: security_group.vpc_id


- name: Create the ELB only listening over port 80
  ec2_elb_lb:
    name: "{{ application }}-load-balancer"
    region: "{{ region }}"
#    vpc_id: "{{ security_group.vpc_id }}"
    security_group_ids: "{{ security_group.group_id }}"
    subnets: "{{ subnet.subnet.id }}"
    #cross_az_load_balancing: "yes"
    state: present
#    zones:
 #     - "{{ region }}a"
  #    - "{{ region }}b"
   #   - "{{ region }}c"
    #  - "{{ region }}d"
     # - "{{ region }}e"
      #- "{{ region }}f"
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
  register: elb

- debug:
    var: elb

- debug:
    var: elb.elb.dns_name
- debug:
    var: elb.elb.hosted_zone_name
- debug:
    var: elb.elb.name
- debug:
    var: elb.elb.security_group_ids
- debug: 
    var: elb.elb.dns_name
- debug: 
    var: elb.elb.instance_health[0].instance_id
- debug: 
    var: elb.elb.instance_health[0].state
- debug: 
    var: elb.elb.instance_health[1].instance_id
- debug: 
    var: elb.elb.instance_health[1].state
- debug: 
    var: elb.elb.instance_health[2].instance_id
- debug: 
    var: elb.elb.instance_health[2].state 
    
- debug:
    var: elb.elb.instances[0]
- debug:
    var: elb.elb.instances[1]
- debug:
    var: elb.elb.instances[2]
- debug:
    var: elb.elb.scheme
- debug:
    var: elb.elb.subnets
- debug:
    var: elb.elb.zones
   

- name: create a new ec2 key pair, returns generated private key
  ec2_key:
    name: "{{ keypair_name }}"
    region: "{{ region }}"
  register: keypair
  tags:
    - ec2_key

- debug:
    var: keypair
  tags:
    - ec2_key

- debug: 
    var: keypair.key.name


- name: Copy EC2 Key Pair private key locally
  copy: content="{{ keypair.key.private_key }}" dest={{ ec2_key_directory_ansible }}ec2_key_pair.ppk owner="{{ keyowner }}" group="{{ keyowner }}" mode=0400
  when: keypair.changed == true
  register: key1
  tags:
    - ec2_key
- debug: 
    var: key1


- debug: 
    msg: "KEY ALREADY EXISTS"
  when: keypair.msg == "key pair already exists"
- debug:
    msg: "NEW KEY PAIR CREATED"
  when: keypair.msg == "key pair created"


- name: Copy EC2 Key Pair private key locally
  copy: content="{{ keypair.key.private_key }}" dest={{ ec2_key_directory_ansible }}ec2_key_pair.pem owner="{{ keyowner }}" group="{{ keyowner }}" mode=0400
  when: keypair.changed == true
  register: key2
  tags:
    - ec2_key
- debug:
    var: key2

- debug:
    msg: "KEY ALREADY EXISTS"
  when: keypair.msg == "key pair already exists"
- debug:
    msg: "NEW KEY PAIR CREATED"
  when: keypair.msg == "key pair created"

- name: Copy EC2 Key Pair private key locally
  copy: content="{{ keypair.key.private_key }}" dest="{{ ec2_key_directory_ansible }}ec2_key_pair.ppk" owner="{{ keyowner }}" group="{{ keyowner }}" mode=0400
  when: keypair.changed == true
  register: key3
  tags:
    - ec2_key
- debug:
    var: key3


- debug:
    msg: "KEY ALREADY EXISTS"
  when: keypair.msg == "key pair already exists"
- debug:
    msg: "NEW KEY PAIR CREATED"
  when: keypair.msg == "key pair created"


- name: Copy EC2 Key Pair private key locally
  copy: content="{{ keypair.key.private_key }}" dest="{{ ec2_key_directory_ansible }}ec2_key_pair.pem" owner="{{ keyowner }}" group="{{ keyowner }}" mode=0400
  when: keypair.changed == true

  register: key4
  tags:
    - ec2_key
- debug:
    var: key4


- debug:
    msg: "KEY ALREADY EXISTS"
  when: keypair.msg == "key pair already exists"

- debug:
    msg: "NEW KEY PAIR CREATED"
  when: keypair.msg == "key pair created"

- name: Create EC2 instances
  ec2:
    key_name: "{{ keypair_name }}"
    image: "{{ verg }}"
    wait: yes
    instance_type: t2.micro
    region: "{{ region }}"
    group_id: "{{ security_group.group_id }}"
    vpc_subnet_id: "{{ subnet.subnet.id }}"
    instance_tags:
      application: "{{ application }}"
    exact_count: "{{ machine_counts }}"
    count_tag:
      application: "{{ application }}"
  register: ec2_instances1

- debug:
    var: ec2_instances1

- name: Store EC2 instance IPs to provision against
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: ec2_instance_ips
  with_items: "{{ ec2_instances1.tagged_instances }}"

- name: Wait for servers to come online
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    timeout: 360
  with_items: "{{ ec2_instances1.tagged_instances }}"

- name: Add EC2 instances as known hosts
  known_hosts:
    name: "{{ item.public_ip }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.public_ip) }}"
  with_items: "{{ ec2_instances1.tagged_instances }}"


