---
- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    application: httpd
    machine_counts: 3
    region: us-east-1
    keypair_name: ec2_key_pair
    cal: "ami-00fc224d9834053d6"
    ore: "ami-087c2c50437d0b80d"
    mum: "ami-0a74bfeb190bd404f"
    verg: "ami-0c322300a1dd5dc79"
    ec2_key_directory_ansible: "/home/ansible/pdauto/"
    keyowner: ansible
  tasks:
    - name: Get my current IP address
      uri:
        url: http://checkip.amazonaws.com/
        return_content: yes
      register: my_ip

    - debug:
        var: my_ip
    - pip: 
        name: boto
    - pip: 
        name: boto3 
    - name: Create simple security group
      ec2_group:
        name: webservers1
        description: A security group for my current IP
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{ my_ip.content | replace('\n', '') }}/32"
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ my_ip.content | replace('\n', '') }}/32"
        rules_egress:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: webserversgroup1
    - debug:
        var: webserversgroup1
    - name: Create the ELB only listening over port 80
      ec2_elb_lb:
        name: "{{ application }}-load-balancer"
        region: "{{ region }}"
        state: present
        zones:
          - "{{ region }}a"
          - "{{ region }}b"
          - "{{ region }}c"
          - "{{ region }}d"
          - "{{ region }}e"
          - "{{ region }}f"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
      register: elb

    - name: create a new ec2 key pair, returns generated private key
      ec2_key:
        name: "{{ keypair_name }}"
        region: "{{ region }}"
      register: keypair
      tags:
        - ec2_key

    - debug:
        var: keypair
      tags:
        - ec2_key


    - name: Copy EC2 Key Pair private key locally
      copy: content="{{ keypair.key.private_key }}" dest={{ ec2_key_directory_ansible }}ec2_key_pair.ppk owner="{{ keyowner }}" group="{{ keyowner }}" mode=0400
      when: keypair.changed == true
      tags:
        - ec2_key


    - name: Copy EC2 Key Pair private key locally
      copy: content="{{ keypair.key.private_key }}" dest={{ ec2_key_directory_ansible }}ec2_key_pair.pem owner="{{ keyowner }}" group="{{ keyowner }}" mode=0400
      when: keypair.changed == true
      tags:
        - ec2_key
    
    - name: Copy EC2 Key Pair private key locally
      copy: content="{{ keypair.key.private_key }}" dest="{{ ec2_key_directory_ansible }}ec2_key_pair.ppk" owner="{{ keyowner }}" group="{{ keyowner }}" mode=0400
      when: keypair.changed == true
      tags:
        - ec2_key


    - name: Copy EC2 Key Pair private key locally
      copy: content="{{ keypair.key.private_key }}" dest="{{ ec2_key_directory_ansible }}ec2_key_pair.pem" owner="{{ keyowner }}" group="{{ keyowner }}" mode=0400
      when: keypair.changed == true
      tags:
        - ec2_key



    - name: Create EC2 instances
      ec2:
        key_name: "{{ keypair_name }}"
        image: "{{ verg }}"
        wait: yes
        instance_type: t2.micro
        region: "{{ region }}"
        group_id:
          - "{{ webserversgroup1.group_id }}"
          - "{{ elb.elb.security_group_ids | first }}"
        instance_tags:
          application: "{{ application }}"
        exact_count: "{{ machine_counts }}"
        count_tag:
          application: "{{ application }}"
      register: ec2_instances

    - debug:
        var: ec2_instances

    - name: Store EC2 instance IPs to provision against
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: ec2_instance_ips
      with_items: "{{ ec2_instances.tagged_instances }}"

    - name: Wait for servers to come online
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        timeout: 360
      with_items: "{{ ec2_instances.tagged_instances }}"

    - name: Add EC2 instances as known hosts
      known_hosts:
        name: "{{ item.public_ip }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.public_ip) }}"
      with_items: "{{ ec2_instances.tagged_instances }}"
      
    - name: print content of key
      command: cat /home/ansible/pdauto/ec2_key_pair.pem
      register: keycontent
    - debug: 
        var: keycontent
    
    
