- hosts: localhost
  vars:
    application: httpd
    machine_counts: 3
    region: us-east-1
  tasks:
     - name: Getting EC2 instances facts
       ec2_instance_facts:
          region: "{{ region }}"
       register: ec2_instances
     - debug: 
          var: ec2_instances
     - name: Gather facts
       action: ec2_facts
       register: ec2
     - debug:
          var: ec2
     - pip:
         name: boto
     - pip: 
         name: boto3
     - name: Add each EC2 instance to the ELB
       ec2_elb:
          state: present
          ec2_elbs: "{{ application }}-load-balancer"
          region: "{{ item.region }}"
          instance_id: "{{ item.id }}"
       with_items: "{{ ec2_instances.instances }}"
