- hosts: localhost
  vars:
    application: httpd
    machine_counts: 3
    region: us-east-1
  tasks:
     - name: pulling running ec2
       ec2:
          region: "{{ region }}"
          state: present
       register: ec2
     - debug: 
          var: ec2
     - name: Add each EC2 instance to the ELB
       ec2_elb:
          state: present
          ec2_elbs: "{{ application }}-load-balancer"
          region: "{{ item.region }}"
          instance_id: "{{ item.id }}"
       with_items: "{{ ec2.tagged_instances }}"
