- hosts: localhost
  vars:
    application: httpd
    machine_counts: 3
    region: us-east-1
  tasks:
     - pip:
         name: boto
     - pip: 
         name: boto3
     - name: Add each EC2 instance to the ELB
       ec2_elb:
          state: present
          ec2_elbs: "{{ application }}-load-balancer"
          region: "{{ item.region }}"
          instance_id: "{{ item.id }}"
       with_items: "{{ ec2_instances.tagged_instances }}"
