---
- hosts: redhat
  tasks:
  - name: Create directory
    file: 
      path: /home/ansible/niranjan 
      state: directory 
      mode: 775 
      owner: ansible 
      group: ansible
    register: directorycreated
  - debug:
      var: directorycreated
