---
- hosts: redhat
  tasks:
    - name: Create multiple directories
      file: 
        path: "{{item}}" 
        state: directory
      with_items:
        - '/home/ansible/vn1'
        - '/home/ansible/vn2'
        - '/home/ansible/vn3'
      register: multipledirectorycreated
    - debug: 
        var: multipledirectorycreated
