---
- hosts: redhat
  tasks:
    - name: stopping nginx
      service:
        name: nginx
        state: stopped

    - name: unInstalling nginx
      yum:
        name: nginx
        state: absent

